//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Custom.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Custom.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 10
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_Custom_Echo_ids[2] =
{
    "::Custom::Echo",
    "::Ice::Object"
};
const ::std::string iceC_Custom_Echo_ops[] =
{
    "echoMessage",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_Custom_Echo_echoMessage_name = "echoMessage";

const ::std::string iceC_Custom_Web_ids[2] =
{
    "::Custom::Web",
    "::Ice::Object"
};
const ::std::string iceC_Custom_Web_ops[] =
{
    "getUrl",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_Custom_Web_getUrl_name = "getUrl";

const ::std::string iceC_Printer_Print_ids[2] =
{
    "::Ice::Object",
    "::Printer::Print"
};
const ::std::string iceC_Printer_Print_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "printSomething"
};
const ::std::string iceC_Printer_Print_printSomething_name = "printSomething";

}

bool
Custom::Echo::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Custom_Echo_ids, iceC_Custom_Echo_ids + 2, s);
}

::std::vector<::std::string>
Custom::Echo::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_Custom_Echo_ids[0], &iceC_Custom_Echo_ids[2]);
}

::std::string
Custom::Echo::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Custom::Echo::ice_staticId()
{
    static const ::std::string typeId = "::Custom::Echo";
    return typeId;
}

/// \cond INTERNAL
bool
Custom::Echo::_iceD_echoMessage(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    int iceP_n;
    istr->readAll(iceP_n);
    inS.endReadParams();
    this->echoMessage(iceP_n, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
Custom::Echo::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Custom_Echo_ops, iceC_Custom_Echo_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Custom_Echo_ops)
    {
        case 0:
        {
            return _iceD_echoMessage(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

bool
Custom::Web::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Custom_Web_ids, iceC_Custom_Web_ids + 2, s);
}

::std::vector<::std::string>
Custom::Web::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_Custom_Web_ids[0], &iceC_Custom_Web_ids[2]);
}

::std::string
Custom::Web::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Custom::Web::ice_staticId()
{
    static const ::std::string typeId = "::Custom::Web";
    return typeId;
}

/// \cond INTERNAL
bool
Custom::Web::_iceD_getUrl(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_s;
    istr->readAll(iceP_s);
    inS.endReadParams();
    this->getUrl(::std::move(iceP_s), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
Custom::Web::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Custom_Web_ops, iceC_Custom_Web_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Custom_Web_ops)
    {
        case 0:
        {
            return _iceD_getUrl(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

bool
Printer::Print::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Printer_Print_ids, iceC_Printer_Print_ids + 2, s);
}

::std::vector<::std::string>
Printer::Print::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_Printer_Print_ids[0], &iceC_Printer_Print_ids[2]);
}

::std::string
Printer::Print::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Printer::Print::ice_staticId()
{
    static const ::std::string typeId = "::Printer::Print";
    return typeId;
}

/// \cond INTERNAL
bool
Printer::Print::_iceD_printSomething(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_s;
    istr->readAll(iceP_s);
    inS.endReadParams();
    this->printSomething(::std::move(iceP_s), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
Printer::Print::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Printer_Print_ops, iceC_Printer_Print_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Printer_Print_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_printSomething(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
Custom::EchoPrx::_iceI_echoMessage(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, int iceP_n, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_Custom_Echo_echoMessage_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_n);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
Custom::EchoPrx::_newInstance() const
{
    return ::IceInternal::createProxy<EchoPrx>();
}
/// \endcond

const ::std::string&
Custom::EchoPrx::ice_staticId()
{
    return Echo::ice_staticId();
}

/// \cond INTERNAL
void
Custom::WebPrx::_iceI_getUrl(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_s, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_Custom_Web_getUrl_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_s);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
Custom::WebPrx::_newInstance() const
{
    return ::IceInternal::createProxy<WebPrx>();
}
/// \endcond

const ::std::string&
Custom::WebPrx::ice_staticId()
{
    return Web::ice_staticId();
}

/// \cond INTERNAL
void
Printer::PrintPrx::_iceI_printSomething(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_s, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_Printer_Print_printSomething_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_s);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
Printer::PrintPrx::_newInstance() const
{
    return ::IceInternal::createProxy<PrintPrx>();
}
/// \endcond

const ::std::string&
Printer::PrintPrx::ice_staticId()
{
    return Print::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_Custom_Echo_echoMessage_name = "echoMessage";

const ::std::string iceC_Custom_Web_getUrl_name = "getUrl";

}

namespace
{

const ::std::string iceC_Printer_Print_printSomething_name = "printSomething";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::Custom::upCast(Echo* p) { return p; }

void
::IceProxy::Custom::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< Echo>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new Echo;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::Custom::Echo::_iceI_begin_echoMessage(::Ice::Int iceP_n, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Custom_Echo_echoMessage_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Custom_Echo_echoMessage_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_n);
        result->endWriteParams();
        result->invoke(iceC_Custom_Echo_echoMessage_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::Custom::Echo::end_echoMessage(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_Custom_Echo_echoMessage_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::Custom::Echo::_newInstance() const
{
    return new Echo;
}
/// \endcond

const ::std::string&
IceProxy::Custom::Echo::ice_staticId()
{
    return ::Custom::Echo::ice_staticId();
}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::Custom::upCast(Web* p) { return p; }

void
::IceProxy::Custom::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< Web>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new Web;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::Custom::Web::_iceI_begin_getUrl(const ::std::string& iceP_s, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Custom_Web_getUrl_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Custom_Web_getUrl_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_s);
        result->endWriteParams();
        result->invoke(iceC_Custom_Web_getUrl_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::Custom::Web::end_getUrl(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_Custom_Web_getUrl_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::Custom::Web::_newInstance() const
{
    return new Web;
}
/// \endcond

const ::std::string&
IceProxy::Custom::Web::ice_staticId()
{
    return ::Custom::Web::ice_staticId();
}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::Printer::upCast(Print* p) { return p; }

void
::IceProxy::Printer::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< Print>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new Print;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::Printer::Print::_iceI_begin_printSomething(const ::std::string& iceP_s, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Printer_Print_printSomething_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Printer_Print_printSomething_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_s);
        result->endWriteParams();
        result->invoke(iceC_Printer_Print_printSomething_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::Printer::Print::end_printSomething(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_Printer_Print_printSomething_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::Printer::Print::_newInstance() const
{
    return new Print;
}
/// \endcond

const ::std::string&
IceProxy::Printer::Print::ice_staticId()
{
    return ::Printer::Print::ice_staticId();
}

Custom::Echo::~Echo()
{
}

/// \cond INTERNAL
::Ice::Object* Custom::upCast(Echo* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_Custom_Echo_ids[2] =
{
    "::Custom::Echo",
    "::Ice::Object"
};

}

bool
Custom::Echo::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Custom_Echo_ids, iceC_Custom_Echo_ids + 2, s);
}

::std::vector< ::std::string>
Custom::Echo::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_Custom_Echo_ids[0], &iceC_Custom_Echo_ids[2]);
}

const ::std::string&
Custom::Echo::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Custom::Echo::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Custom::Echo";
    return typeId;
#else
    return iceC_Custom_Echo_ids[0];
#endif
}

/// \cond INTERNAL
bool
Custom::Echo::_iceD_echoMessage(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Int iceP_n;
    istr->read(iceP_n);
    inS.endReadParams();
    this->echoMessage(iceP_n, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_Custom_Echo_all[] =
{
    "echoMessage",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

/// \cond INTERNAL
bool
Custom::Echo::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Custom_Echo_all, iceC_Custom_Echo_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Custom_Echo_all)
    {
        case 0:
        {
            return _iceD_echoMessage(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
Custom::Echo::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< Echo, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
Custom::Echo::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< Echo, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
Custom::_icePatchObjectPtr(EchoPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = EchoPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(Echo::ice_staticId(), v);
    }
}
/// \endcond

Custom::Web::~Web()
{
}

/// \cond INTERNAL
::Ice::Object* Custom::upCast(Web* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_Custom_Web_ids[2] =
{
    "::Custom::Web",
    "::Ice::Object"
};

}

bool
Custom::Web::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Custom_Web_ids, iceC_Custom_Web_ids + 2, s);
}

::std::vector< ::std::string>
Custom::Web::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_Custom_Web_ids[0], &iceC_Custom_Web_ids[2]);
}

const ::std::string&
Custom::Web::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Custom::Web::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Custom::Web";
    return typeId;
#else
    return iceC_Custom_Web_ids[0];
#endif
}

/// \cond INTERNAL
bool
Custom::Web::_iceD_getUrl(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_s;
    istr->read(iceP_s);
    inS.endReadParams();
    this->getUrl(iceP_s, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_Custom_Web_all[] =
{
    "getUrl",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

/// \cond INTERNAL
bool
Custom::Web::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Custom_Web_all, iceC_Custom_Web_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Custom_Web_all)
    {
        case 0:
        {
            return _iceD_getUrl(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
Custom::Web::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< Web, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
Custom::Web::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< Web, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
Custom::_icePatchObjectPtr(WebPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = WebPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(Web::ice_staticId(), v);
    }
}
/// \endcond

Printer::Print::~Print()
{
}

/// \cond INTERNAL
::Ice::Object* Printer::upCast(Print* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_Printer_Print_ids[2] =
{
    "::Ice::Object",
    "::Printer::Print"
};

}

bool
Printer::Print::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Printer_Print_ids, iceC_Printer_Print_ids + 2, s);
}

::std::vector< ::std::string>
Printer::Print::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_Printer_Print_ids[0], &iceC_Printer_Print_ids[2]);
}

const ::std::string&
Printer::Print::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Printer::Print::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Printer::Print";
    return typeId;
#else
    return iceC_Printer_Print_ids[1];
#endif
}

/// \cond INTERNAL
bool
Printer::Print::_iceD_printSomething(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_s;
    istr->read(iceP_s);
    inS.endReadParams();
    this->printSomething(iceP_s, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_Printer_Print_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "printSomething"
};

}

/// \cond INTERNAL
bool
Printer::Print::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Printer_Print_all, iceC_Printer_Print_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Printer_Print_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_printSomething(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
Printer::Print::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< Print, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
Printer::Print::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< Print, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
Printer::_icePatchObjectPtr(PrintPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = PrintPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(Print::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

namespace Ice
{
}

#endif
